# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(937, 808)
        self.playBoard = QtWidgets.QTableWidget(Dialog)
        self.playBoard.setGeometry(QtCore.QRect(0, 0, 751, 751))
        self.playBoard.setMinimumSize(QtCore.QSize(751, 0))
        font = QtGui.QFont()
        font.setFamily("IPAGothic")
        font.setPointSize(15)
        self.playBoard.setFont(font)
        self.playBoard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.playBoard.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.playBoard.setTextElideMode(QtCore.Qt.ElideRight)
        self.playBoard.setColumnCount(12)
        self.playBoard.setObjectName("playBoard")
        self.playBoard.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playBoard.setItem(0, 0, item)
        self.playBoard.horizontalHeader().setDefaultSectionSize(60)
        self.playBoard.horizontalHeader().setMinimumSectionSize(36)
        self.playBoard.verticalHeader().setDefaultSectionSize(60)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(760, 10, 77, 18))
        font = QtGui.QFont()
        font.setFamily("IPAGothic")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(760, 40, 91, 18))
        font = QtGui.QFont()
        font.setFamily("IPAGothic")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.rowLabel = QtWidgets.QLabel(Dialog)
        self.rowLabel.setGeometry(QtCore.QRect(850, 40, 91, 18))
        font = QtGui.QFont()
        font.setFamily("IPAGothic")
        font.setPointSize(13)
        self.rowLabel.setFont(font)
        self.rowLabel.setObjectName("rowLabel")
        self.columnLabel = QtWidgets.QLabel(Dialog)
        self.columnLabel.setGeometry(QtCore.QRect(850, 10, 77, 18))
        font = QtGui.QFont()
        font.setFamily("IPAGothic")
        font.setPointSize(13)
        self.columnLabel.setFont(font)
        self.columnLabel.setObjectName("columnLabel")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(830, 700, 94, 51))
        self.startButton.setObjectName("startButton")
        self.setColumn = QtWidgets.QSpinBox(Dialog)
        self.setColumn.setGeometry(QtCore.QRect(770, 724, 54, 27))
        self.setColumn.setMinimum(1)
        self.setColumn.setMaximum(12)
        self.setColumn.setProperty("value", 12)
        self.setColumn.setObjectName("setColumn")
        self.setRow = QtWidgets.QSpinBox(Dialog)
        self.setRow.setGeometry(QtCore.QRect(770, 694, 54, 27))
        self.setRow.setMinimum(1)
        self.setRow.setMaximum(12)
        self.setRow.setProperty("value", 12)
        self.setRow.setObjectName("setRow")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.playBoard.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.playBoard.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.playBoard.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.playBoard.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.playBoard.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.playBoard.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.playBoard.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.playBoard.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.playBoard.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.playBoard.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.playBoard.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.playBoard.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.playBoard.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        __sortingEnabled = self.playBoard.isSortingEnabled()
        self.playBoard.setSortingEnabled(False)
        self.playBoard.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog", "Column:"))
        self.label_2.setText(_translate("Dialog", "Row   :"))
        self.rowLabel.setText(_translate("Dialog", "R"))
        self.columnLabel.setText(_translate("Dialog", "C"))
        self.startButton.setText(_translate("Dialog", "GAME START"))


